apiVersion: apps/v1
kind: Deployment
metadata:
  name: task18-test1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task18-test1
  template:
    metadata:
      labels:
        app: task18-test1
    spec:
      containers:
      - name: task18-test1
        image: nginx:1.19
        ports:
        - containerPort: 80
